project:
  type: website

website:
  site-url: "https://www.liaoyjruby.com"
  title: "Yi Jou (Ruby) Liao"
  favicon: kyute.png
  twitter-card:
    creator: "@liaoyjruby"
  open-graph: true
  navbar:
    logo: kyute.png
    search: false
    background: "primary"
    left:
      - text: "Blog"
        file: rublog.qmd
      - text: "CV"
        file: cv.qmd
  google-analytics: 
    tracking-id: "G-CGMN9S98KJ"
    storage: none

format:
  html:
    theme:
        light: [flatly, theme-light.scss]
        dark: [darkly, theme-dark.scss]
    css: styles.css



