project:
  type: website
  output-dir: docs

website:
  twitter-card: true
  title: "Yi Jou (Ruby) Liao"
  navbar:
    search: false
    background: "primary"
    right:
      - text: "About"
        file: index.qmd
      - text: "Blog"
        file: rublog.qmd
    tools:
      - icon: github
        href:  https://github.com/liaoyjruby
      - icon: twitter
        href: https://twitter.com/liaoyjruby
format:
  html:
    theme:
        light: [flatly, theme-light.scss]
        dark: [darkly, theme-dark.scss]
    css: styles.css



